channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cmake>=3.14.0
  - cudatoolkit>=10.1.0
  - cudnn
  - numpy>=1.18.1
  - pytorch>=1.5.0
  - scipy>=1.4.1
  - matplotlib>=3.1.3
  - pip>=19.0.0
  - pip:
      - opencv-python>=3.1.0
      - scikit-build
      - pypfm
